"""001_phase1_schema

Revision ID: 62bb5cdc1ec8
Revises: 
Create Date: 2026-05-10 18:26:46.437497
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '62bb5cdc1ec8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('attribution_text', sa.Text(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetch_frequency', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingest_errors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_errors_source'), 'ingest_errors', ['source'], unique=False)
    op.create_table('jurisdictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('fips_code', sa.String(length=10), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['jurisdictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jurisdictions_fips_code'), 'jurisdictions', ['fips_code'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('persons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('bioguide_id', sa.String(length=20), nullable=True),
    sa.Column('fec_candidate_id', sa.String(length=20), nullable=True),
    sa.Column('openstates_id', sa.String(length=50), nullable=True),
    sa.Column('wikidata_qid', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_bioguide_id'), 'persons', ['bioguide_id'], unique=True)
    op.create_index(op.f('ix_persons_fec_candidate_id'), 'persons', ['fec_candidate_id'], unique=False)
    op.create_index(op.f('ix_persons_openstates_id'), 'persons', ['openstates_id'], unique=False)
    op.create_index(op.f('ix_persons_wikidata_qid'), 'persons', ['wikidata_qid'], unique=False)
    op.create_table('offices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('chamber', sa.String(length=50), nullable=True),
    sa.Column('jurisdiction_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_external_ids',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'source_name', name='uq_person_source')
    )
    op.create_index(op.f('ix_person_external_ids_person_id'), 'person_external_ids', ['person_id'], unique=False)
    op.create_table('officeholders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('party_id', sa.Uuid(), nullable=True),
    sa.Column('jurisdiction_id', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('data_source_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_officeholders_is_current'), 'officeholders', ['is_current'], unique=False)
    op.create_index(op.f('ix_officeholders_person_id'), 'officeholders', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_officeholders_person_id'), table_name='officeholders')
    op.drop_index(op.f('ix_officeholders_is_current'), table_name='officeholders')
    op.drop_table('officeholders')
    op.drop_index(op.f('ix_person_external_ids_person_id'), table_name='person_external_ids')
    op.drop_table('person_external_ids')
    op.drop_table('offices')
    op.drop_index(op.f('ix_persons_wikidata_qid'), table_name='persons')
    op.drop_index(op.f('ix_persons_openstates_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_fec_candidate_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_bioguide_id'), table_name='persons')
    op.drop_table('persons')
    op.drop_table('parties')
    op.drop_index(op.f('ix_jurisdictions_fips_code'), table_name='jurisdictions')
    op.drop_table('jurisdictions')
    op.drop_index(op.f('ix_ingest_errors_source'), table_name='ingest_errors')
    op.drop_table('ingest_errors')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
